import { Borrower, Loan } from "@/types";


// Mock data to simulate a fetch from a database
export const MOCK_BORROWERS: Borrower[] = [
    {
        id: 'B001',
        name: 'Jane Doe',
        phone: '123-456-7890',
        totalLoansTaken: 5,
        activeLoans: 2,
        outstandingBalance: 1500,
        status: 'Active',
    },
    {
        id: 'B002',
        name: 'John Smith',
        phone: '987-654-3210',
        totalLoansTaken: 1,
        activeLoans: 1,
        outstandingBalance: 750,
        status: 'Overdue',
    },
    {
        id: 'B003',
        name: 'Sarah Connor',
        phone: '555-123-4567',
        totalLoansTaken: 12,
        activeLoans: 3,
        outstandingBalance: 3200,
        status: 'Active',
    },
    {
        id: 'B004',
        name: 'Michael Jordan',
        phone: '111-222-3333',
        totalLoansTaken: 8,
        activeLoans: 1,
        outstandingBalance: 500,
        status: 'Overdue',
    },
    {
        id: 'B005',
        name: 'Emily White',
        phone: '444-555-6666',
        totalLoansTaken: 3,
        activeLoans: 1,
        outstandingBalance: 900,
        status: 'Active',
    },
    {
        id: 'B006',
        name: 'David Brown',
        phone: '777-888-9999',
        totalLoansTaken: 6,
        activeLoans: 2,
        outstandingBalance: 1800,
        status: 'Active',
    },
    {
        id: 'B007',
        name: 'Olivia Davis',
        phone: '222-333-4444',
        totalLoansTaken: 2,
        activeLoans: 1,
        outstandingBalance: 250,
        status: 'Overdue',
    },
];

// Dummy data for demonstration purposes, now typed with the Loan interface.
export const MOCK_LOANS: Loan[] = [
    {
        id: 'L001',
        borrower: 'John Doe',
        amount: 500.00,
        startDate: '2023-01-15',
        dueDate: '2023-03-15',
        status: 'Active',
        remainingBalance: 300.00,
    },
    {
        id: 'L002',
        borrower: 'Jane Smith',
        amount: 1200.00,
        startDate: '2022-12-01',
        dueDate: '2023-02-01',
        status: 'Paid',
        remainingBalance: 0.00,
    },
    {
        id: 'L003',
        borrower: 'Peter Jones',
        amount: 750.00,
        startDate: '2023-01-20',
        dueDate: '2023-02-20',
        status: 'Overdue',
        remainingBalance: 750.00,
    },
    {
        id: 'L004',
        borrower: 'Sarah Connor',
        amount: 2500.00,
        startDate: '2023-02-01',
        dueDate: '2023-05-01',
        status: 'Active',
        remainingBalance: 1500.00,
    },
    {
        id: 'L005',
        borrower: 'Michael Vance',
        amount: 900.00,
        startDate: '2023-01-10',
        dueDate: '2023-03-10',
        status: 'Paid',
        remainingBalance: 0.00,
    },
];