import { ActiveLoan, LoanRequest } from "@/types";

export const mockActiveLoan: ActiveLoan = {
    id: 'loan-001',
    totalAmount: 5000,
    amountPaid: 1500,
    nextDueDate: 'Oct 15, 2025',
    status: 'Active',
};

export const mockLoanRequests: LoanRequest[] = [
    {
        id: 'req-001',
        borrower: { name: 'Fatima Zahra', reputation: 'Trusted' },
        purpose: 'Small Business Inventory',
        amountNeeded: 2500,
        amountFunded: 1800,
        deadline: '25 Days Left',
    },
    {
        id: 'req-002',
        borrower: { name: 'Yusuf Ali', reputation: 'Good' },
        purpose: 'Educational Fees',
        amountNeeded: 1200,
        amountFunded: 500,
        deadline: '10 Days Left',
    },
    {
        id: 'req-003',
        borrower: { name: 'Aisha Siddiqui', reputation: 'New' },
        purpose: 'Emergency Medical Bill',
        amountNeeded: 800,
        amountFunded: 800,
        deadline: 'Funded',
    },
    {
        id: 'req-004',
        borrower: { name: 'Omar Farooq', reputation: 'Trusted' },
        purpose: 'Home Repair',
        amountNeeded: 3000,
        amountFunded: 1100,
        deadline: '30 Days Left',
    },
    {
        id: 'req-004',
        borrower: { name: 'Omar Farooq', reputation: 'Trusted' },
        purpose: 'Home Repair',
        amountNeeded: 3000,
        amountFunded: 1100,
        deadline: '30 Days Left',
    },
    {
        id: 'req-004',
        borrower: { name: 'Omar Farooq', reputation: 'Trusted' },
        purpose: 'Home Repair',
        amountNeeded: 3000,
        amountFunded: 1100,
        deadline: '30 Days Left',
    },
    {
        id: 'req-004',
        borrower: { name: 'Omar Farooq', reputation: 'Trusted' },
        purpose: 'Home Repair',
        amountNeeded: 3000,
        amountFunded: 1100,
        deadline: '30 Days Left',
    },
    {
        id: 'req-004',
        borrower: { name: 'Omar Farooq', reputation: 'Trusted' },
        purpose: 'Home Repair',
        amountNeeded: 3000,
        amountFunded: 1100,
        deadline: '30 Days Left',
    },
    {
        id: 'req-004',
        borrower: { name: 'Omar Farooq', reputation: 'Trusted' },
        purpose: 'Home Repair',
        amountNeeded: 3000,
        amountFunded: 1100,
        deadline: '30 Days Left',
    },
    {
        id: 'req-004',
        borrower: { name: 'Omar Farooq', reputation: 'Trusted' },
        purpose: 'Home Repair',
        amountNeeded: 3000,
        amountFunded: 1100,
        deadline: '30 Days Left',
    },
    {
        id: 'req-004',
        borrower: { name: 'Omar Farooq', reputation: 'Trusted' },
        purpose: 'Home Repair',
        amountNeeded: 3000,
        amountFunded: 1100,
        deadline: '30 Days Left',
    },
    {
        id: 'req-004',
        borrower: { name: 'Omar Farooq', reputation: 'Trusted' },
        purpose: 'Home Repair',
        amountNeeded: 3000,
        amountFunded: 1100,
        deadline: '30 Days Left',
    },
    {
        id: 'req-004',
        borrower: { name: 'Omar Farooq', reputation: 'Trusted' },
        purpose: 'Home Repair',
        amountNeeded: 3000,
        amountFunded: 1100,
        deadline: '30 Days Left',
    },
    {
        id: 'req-004',
        borrower: { name: 'Omar Farooq', reputation: 'Trusted' },
        purpose: 'Home Repair',
        amountNeeded: 3000,
        amountFunded: 1100,
        deadline: '30 Days Left',
    },
    {
        id: 'req-004',
        borrower: { name: 'Omar Farooq', reputation: 'Trusted' },
        purpose: 'Home Repair',
        amountNeeded: 3000,
        amountFunded: 1100,
        deadline: '30 Days Left',
    },
    {
        id: 'req-004',
        borrower: { name: 'Omar Farooq', reputation: 'Trusted' },
        purpose: 'Home Repair',
        amountNeeded: 3000,
        amountFunded: 1100,
        deadline: '30 Days Left',
    },
    {
        id: 'req-004',
        borrower: { name: 'Omar Farooq', reputation: 'Trusted' },
        purpose: 'Home Repair',
        amountNeeded: 3000,
        amountFunded: 1100,
        deadline: '30 Days Left',
    },
    {
        id: 'req-004',
        borrower: { name: 'Omar Farooq', reputation: 'Trusted' },
        purpose: 'Home Repair',
        amountNeeded: 3000,
        amountFunded: 1100,
        deadline: '30 Days Left',
    },
];